### PR TITLE
Use tello_ros instead of TelloPy, migrate image pipeline to C++

### PR DESCRIPTION
**Pull request by clydemcqueen**
Big refactor:
* use tello_ros instead of TelloPy + flock_driver.py
* better state management
* aruco detection in C++
* usb_camera in C++
* test in Crystal (no changes)

Some tweaks left, but pretty much done, waiting for flock_vlam. :-)

### CODE REVIEW

**Comment by ptrmu** [comment]
Looks excellent. I love your use of eigen! You should put header double-include prevention in eigen_util.hpp. I'm copying your great code and that bit me.

**Comment by clydemcqueen** [comment]
Good feedback. I'll add that.

**Comment by clydemcqueen** [comment]
Hmmm... I'm seeing warnings from canTransform when I run a mission. I'll debug these.

**Comment by clydemcqueen** [comment]
OK, fixed warnings and cleaned up a few things.

There's more work to get missions to start/stop successfully, but this isn't related to the refactoring here. I'm going to merge this and continue to work on the mission planner as a separate effort.

**Pull request merged**
